### ISSUE TITLE
유저 정보를 제공하는 로직 구현

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [boostcampwm-2024/iOS09-BeStory#3]
## 💡 요약

유저들의 정보를 제공하는 Socket 로직 구현 이슈입니다.

## 💻 Todo
- [ ] SockerProvider 기초 구현
- [ ] 주변 유저의 리스트 가져오기
- [ ] 주변 유저의 변화 실시간 업데이트 내보내기
