### ISSUE TITLE
레이더 형태로 주변 유저 목록을 표시하는 UI설계

### ISSUE THREAD

**Issue by LURKS02** [boostcampwm-2024/iOS09-BeStory#4]
# 💡 요약

홈 화면에서 레이더 형태로 주변 유저 목록을 표시하는 UI 입니다.

# 💻 Todo
 ### UI 구현사항

- [x] ViewController로 구현
- [x] 랜덤 위치에 캐릭터 생성 (캐릭터가 겹치지 않게 배치)
- [x] 모든 유저 캐릭터는 일단 랜덤 컬러 뷰로 구현 (추후 이미지 추가 등 고려)
- [x] 다른 유저 캐릭터를 탭하여 그룹 을 진행한다.

### 로직 구현사항

- [x] 표시해야할 유저들을 겹치지 않게 하는 로직
