### ISSUE TITLE
Wiki 기술 문서 및 트러블 슈팅 업데이트

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [boostcampwm-2024/iOS09-BeStory#54]
## 💡 요약

Wiki 기술 문서 및 트러블 슈팅 업데이트입니다.

## 💻 Todo

- [ ]  1회차 기술공유 문서화
- [ ]  MultiPeer Connectivity State 트러블 슈팅 업데이트
- [ ]  Embeded관련 트러블 슈팅 업데이트
