### ISSUE TITLE
참가한 그룹에서 퇴장하는 로직을 구현하고 뷰와 연결한다.

### ISSUE THREAD

**Issue by 051198Hz** [boostcampwm-2024/iOS09-BeStory#58]
## 💡 요약

참가한 그룹에서 퇴장하고, 이를 뷰에 반영하기 위한 로직을 구현합니다.

## 💻 Todo

- [x]  SocketProvider에서 퇴장 로직 구현
- [x] Repository, Usecase에서 퇴장함에 따른 피어 정보 변경 방출
- [x] 뷰에서 퇴장 버튼과 로직을 연결하고, 퇴장 시 연결된 모든 피어들의 정보를 보여주는 뷰 제거
