### ISSUE TITLE
공유 편집화면의 상단부 동영상 띄우는 화면에서 영상 길이를 조절할 수 있다.

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [boostcampwm-2024/iOS09-BeStory#64]
## 💡 요약

공유 편집화면의 동영상 띄우는 화면에서 영상길이 조절 기능 구현

## 💻 Todo

- [x] 영상 frame단위로 표시되는 기능 
- [x] 영상의 앞 뒤에서 길이를 조절할 수 있는 기능 
- [x] 영상의 재생되는 위치에 display하는 기능 
- [x] 상위 뷰로 이벤트를 전달할 수 있는 기능
