### ISSUE TITLE
CRDT에 사용할 VectorClock을 통해 변경사항 추적이 가능해야 한다.

### ISSUE THREAD

**Issue by 051198Hz** [boostcampwm-2024/iOS09-BeStory#68]
## 💡 요약

VectorClock구현 및 LWWElementSet에 VectorClock을 적용

## 💻 Todo

- [x] VectorClock구현
- [x] LWWElementSet에 VectorClock을 적용
- [x] LWWElementSet의 상태 변화를 방출할 수 있는 기능 구현
- [x] LWWElementSet을 송/수신할 수 있도록 인코딩/디코딩 기능 구현
