### ISSUE TITLE
공유 편집화면에서 실시간 변경사항을 UI에 반영한다.

### ISSUE THREAD

**Issue by around-forest** [boostcampwm-2024/iOS09-BeStory#76]
## 💡 요약

UseCase와 편집화면 ViewModel-ViewController를 연결하는 작업입니다.

## 💻 Todo

- [x]  UseCase와 ViewModel 연결
- [x] ViewModel과 ViewController 연결
- [ ] 연결에 따른 동작 확인 및 버그 수정
