### ISSUE TITLE
타임라인  내 동영상의 순서를 변경하고 길이를 편집하는 비즈니스 로직을 구현한다.

### ISSUE THREAD

**Issue by 051198Hz** [boostcampwm-2024/iOS09-BeStory#82]
## 💡 요약

타임라인 내 동영상의 순서를 변경하고 길이를 편집하는 비즈니스 로직을 구현한다.

## 💻 Todo

- [ ] 뷰의 타임라인 내 동영상의 순서 변경을 ViewModel과 연결
- [ ] ViewModel의 변경사항을 처리할 UseCase의 구현
- [ ] UseCase와 ViewModel의 연결
- [ ] UseCase와 외부의 변경사항을 방출하는 Repository와 연결

**Comment by 051198Hz** [comment]
다른 작업과 겹침으로 인해 해당 작업들에 대한 PR이 머지된 후 후속작업 예정으로 이슈를 닫습니다.
